import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Footer from './components/footer'
import Header from './components/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" className=" scroll-smooth ">
            <body
                className={`${inter.className} flex min-h-screen overflow-clip flex-col bg-sky-500`}
            >
                <Header />
                <main className="flex-auto bg-slate-300">{children}</main>
                <Footer />
            </body>
        </html>
    )
}
